version: "3.9"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    volumes:
      - ../postgres/init.sql:/docker-entrypoint-initdb.d/init.sql